name: Publish
on:
    workflow_run:
        workflows: [CI]
        branches: [main]
        types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
    contents: write
    pull-requests: write

jobs:
    publish:
        if: ${{ github.event.workflow_run.conc